import type { ExplanationLevel } from "@/lib/data";

export interface AboutSection {
  headline: string;
  body: Record<ExplanationLevel, string>;
}

export const ABOUT_SECTIONS: AboutSection[] = [
  {
    headline: "YOU'VE BEEN WATCHING THE WEATHER REPORT. NOT THE ACTUAL WEATHER.",
    body: {
      kid: "The news tells you how to feel about the economy. A politician says something. Someone else disagrees. But nobody shows you the real numbers — like that the government said they had a '$10 billion surplus' while actually the cash deficit was $15.8 billion. Or that $85 billion in spending doesn't even appear in the headline because it's called 'investment' not 'spending.' Or that Australia's economy only looked like it grew because we added more people — for six quarters in a row, each person got poorer on average. This site shows you what actually happened.",
      teen: "Every night, the news tells you how to feel about the economy. A journalist interviews a politician. The politician says something. An economist disagrees. A commentator has a hot take. Nobody shows you the spreadsheet. Nobody shows you that the government reported a '$10 billion surplus' while simultaneously running a $15.8 billion cash deficit. Nobody explains that there's $85 billion in spending next year that doesn't appear in the headline deficit figure — because it's classified as 'investment' not 'spending.' Nobody tells you that Australia's GDP grew — but GDP per capita fell for six consecutive quarters. Meaning the economy only looked okay because we added more people, not because each person got wealthier. The media covers politics. Politics is about who wins. This site covers finances. Finances are about what actually happened. These are not the same thing.",
      expert: "Media coverage of government finance is structurally constrained: Budget Papers (1,200+ pages) are released with ~3 hours before evening deadlines; coverage follows the government's press release. ANAO audit reports (significant findings on capitalisation, asset valuations, accounting practices) are released months later and are rarely covered. Commonwealth Consolidated Financial Statements — audited accounts, reconciliation of budget vs actual, disclosure of movements (e.g. $95B superannuation actuarial) — are released Nov/Dec and are essentially never covered. Result: public narrative tracks political framing, not primary sources. This site surfaces the primary sources and makes them readable. No interpretation layer beyond structural presentation and same methodology for all parties.",
    },
  },
  {
    headline: "THE PRIMARY SOURCES. FINALLY READABLE.",
    body: {
      kid: "Every number on this site comes from the real books: (1) The Commonwealth Consolidated Financial Statements — the government's actual accounts, checked by the government's own auditors. (2) The ANAO Audit Reports — where those auditors say what they're worried about. They've raised concerns every year across the 25-year dataset. (3) The Budget Papers — what the government says it will do. We compare that to what actually happened. We've made the primary sources readable. Then we built tools so you can see what the numbers mean for your life.",
      teen: "Every number on this site comes from one of three places: (1) The Commonwealth Consolidated Financial Statements — published annually by the Department of Finance, audited by the ANAO. The actual books. The real numbers. 500+ pages most Australians never see. (2) The ANAO Audit Reports — the government's own auditors flagging what they're worried about. They've raised concerns about military asset valuations, capitalisation decisions, and accounting practices — every single year across the 25-year dataset. Nobody reports this. (3) The Budget Papers — the government's own forward estimates. Their promises, in writing. We compare these to what actually happened. We've done none of the interpretation. We've just made the primary sources readable. And then we've built tools to help you understand what the numbers actually mean for your daily life.",
      expert: "Data sources: (1) Commonwealth CFS — Department of Finance, GFS framework, ANAO audited. (2) ANAO — financial statement audit, performance audit, significant and moderate findings time series. (3) Budget Papers — BP1–3, forward estimates, Mid-Year Economic and Fiscal Outlook. No proprietary or paywalled data. All sources publicly available. We aggregate, cite, and present; methodology is documented in README and PHILOSOPHY.md. No editorial interpretation beyond structural choices (e.g. Fair Centre baseline, Cooked Metre formula) which are applied identically to all parties.",
    },
  },
  {
    headline: "PICK YOUR LEVEL. GET THE TRUTH.",
    body: {
      kid: "Not everyone wants the same amount of detail. So everything on this site has three modes: Plain English (for anyone — simple words, no jargon), Straight Talk (facts and numbers without the heavy stuff), and Deep Dive (full technical detail, the kind you'd need to argue with an economist). Same data. Three ways in. You choose.",
      teen: "We know not everyone wants the same depth of explanation. So everything on this site has three modes: Plain English — for anyone. Analogies. Simple language. No assumptions. Straight Talk — for people who want facts without jargon. Numbers, context, what it means. No economics degree required. Deep Dive — for people who want the full picture. Technical terms. Policy nuance. Primary source citations. Everything you'd need to have an informed argument with an economist. The same data. Three ways in. You choose your depth.",
      expert: "Three-level explanation system: (1) Kid/Plain English — analogies, no assumed knowledge, accessible to general audience. (2) Teen/Straight Talk — factual, numeric, context without discipline-specific jargon. (3) Expert/Deep Dive — technical terminology, policy nuance, source citations, defensible for informed debate. Implemented via LevelContext; all explainer content keyed by ExplanationLevel. Ensures accessibility without dumbing down; experts can verify against primary sources.",
    },
  },
  {
    headline: "WHAT WOULD ACTUALLY FAIR LOOK LIKE?",
    body: {
      kid: "Both sides say they're managing the economy responsibly. Both say the other is lying. We built a mathematical baseline for what a centrist, evidence-based government would actually do — not left, not right, just what the data from other countries and long-run averages says is sustainable. We score every government against it across the full 25-year period. Neither party gets a pass. The most centrist year in the dataset? Howard's 2006-07 (net debt eliminated). In recent years, 2018-19. The year nobody talks about.",
      teen: "Both sides of politics claim to be managing the economy responsibly. Both sides claim the other side is lying. We built something different: a mathematical baseline for what a centrist, evidence-based government would actually do. Not left. Not right. Just: what does the data from comparable countries, long-run Australian averages, and independent economic institutions say is structurally sustainable? We call this the Fair Centre baseline. Then we score every government against it across 25 years. The result: neither party gets a pass. Howard years were near or above-centre fiscally. Coalition and Labor since the GFC have run left-of-centre on spending. The most centrist year in the full 25-year period: 2006-07. In the recent period, 2018-19.",
      expert: "Fair Centre baseline: structural revenue/expense as % GDP derived from long-run averages, OECD comparators, and Treasury/independent institution estimates. CENTRE object in lib/data.ts (revPct, expPct, cashPct, debtPct). politicalLean scores deviation from centre; positive = left of centre (higher revenue/spend), negative = right. Howard era 2004-07 closest to centre; 2018-19 best in post-GFC period. Coalition pre-COVID structurally below-centre revenue; Labor post-2022 above-centre revenue from terms-of-trade windfall, deployed to spending. Methodology documented in README and data.ts.",
    },
  },
  {
    headline: "IS THIS PM ACTUALLY COOKED?",
    body: {
      kid: "The Cooked Metre isn't about who you voted for. It scores Prime Ministers on things we can measure: Did the economy grow per person? Did real wages go up or down? Did they do what they promised? What do fact-checkers say? Did immigration match what they said they'd plan for? What did the government's own auditors flag? Every score links to the source. You can check every number yourself. If you think we're wrong, raise a GitHub issue.",
      teen: "The Cooked Metre is not about who you voted for. It's not about policies you agree or disagree with. It scores Prime Ministers on measurable, verifiable outcomes: Did the economy grow per capita? Did real wages go up or down? Did they deliver what they promised? What do independent fact-checkers say about their statements? Did immigration match the housing capacity they planned for? What did the government's own auditors flag? Every score links to the source. RMIT FactLab. ABS data. ANAO reports. Parliamentary Budget Office. You can click through and verify every single number yourself. If you think a score is wrong, raise a GitHub issue. We'll look at the evidence and update it if you're right.",
      expert: "Cooked Metre: 8 factors (Economic Reality, Cost of Living, Fiscal, Immigration, Wages, Deception, Governance, Long-term Damage), weighted. Raw score = weighted average. Deception is a multiplier: final = min(100, raw × (1 + deception/100 × 0.30)). Economic metrics per capita. Immigration scored on accountability to own NOM forecasts and housing/per-capita impact, not migration policy. All scores cite sources; methodology identical for all PMs. See lib/pm-data.ts, getAlgorithmDescription(), AGENT.md.",
    },
  },
  {
    headline: "VERIFY EVERYTHING. CHALLENGE ANYTHING.",
    body: {
      kid: "This entire site is open source. Every line of code is visible. Every number has a source link. The AI's instructions are in the code. The scoring rules are written down. Anyone can copy the project and check the results. The moment you have to trust us, we've failed. You should be able to verify us. If someone says we're wrong, they can raise a GitHub issue. We'll look at the evidence and fix it if they're right.",
      teen: "This entire site is open source. That means: every line of code is publicly visible on GitHub; every data point is cited with a source URL; the AI chatbot's system prompt is visible in the source code; the scoring algorithms are documented in detail; anyone can fork this project, run it themselves, and verify the results. We've done this deliberately. The moment you have to trust us, we've failed. You should never have to trust us. You should be able to verify us. If a politician or journalist claims we've got something wrong, they can raise a GitHub issue like anyone else. We'll publish the evidence and update the data if they're correct. This is how accountability should work.",
      expert: "Full repo: GitHub public. lib/data.ts, lib/pm-data.ts: all figures with source comments/URLs. AI system prompt in source (chat). Scoring: getAlgorithmDescription(), FACTOR_WEIGHTS, computeFinalScore. No proprietary data. No paywall. Forkable, buildable, verifiable. Contribution: CONTRIBUTING.md. Data correction process: issue with source document → 48h response → public evidence → merge if verified. Political neutrality: methodology same for all parties; PRs that apply different rules to different parties are rejected.",
    },
  },
  {
    headline: "LET'S BE CLEAR ABOUT WHAT WE'RE NOT.",
    body: {
      kid: "We're not telling you how to vote. We're not for or against any party. We're not paid by any party, lobby group, or media company. We don't run ads. We don't have a view on immigration as a policy, or climate policy, or social policy. What we do have a view on: the numbers should be public and readable; governments should be held to what they said; decisions should be based on data, not spin; the same rules for everyone. If you're Labor, you'll find things here that challenge you. If you're Coalition, same. That's the point.",
      teen: "This site is not telling you how to vote. This site is not anti-Labor or anti-Coalition. This site is not funded by any political party, lobby group, media organisation, or government body. This site does not take advertising. This site does not have a view on immigration as a policy. This site does not have a view on climate policy. This site does not have a view on social policy. What this site HAS a view on: Transparency. The numbers should be public and readable. Accountability. Governments should be held to what they actually said. Evidence. Decisions should be based on data, not narrative. Fairness. The same methodology applied to everyone, equally. If you're Labor, you'll find things here that challenge you. If you're Coalition, you'll find things here that challenge you. If you're a swing voter, you'll find things here that cut through the noise and let you make a more informed decision. That's the point.",
      expert: "Scope boundaries: no voting recommendation; no party affiliation; no funding from political/lobby/media/government; no advertising; no policy stance on immigration, climate, or social policy (Immigration factor scores accountability-to-forecast only). Stance: transparency (public, readable data), accountability (governments held to stated commitments), evidence (data over narrative), fairness (identical methodology for all). Methodology is public; results will challenge all partisan priors. Design goal: any Australian can verify methodology and disagree on interpretation without doubting equal application.",
    },
  },
  {
    headline: "WHERE THIS IS GOING.",
    body: {
      kid: "We're building an AI agent that will update this site automatically. When new official data comes out — from the ABS, or fact-checkers, or the budget — the site updates. The goal is a permanent, living record of Australian government finances. Always current. Always cited. This isn't a media project. It's infrastructure. Like roads and electricity — it should just exist. For everyone. For free.",
      teen: "We're building an AI agent that will update this site automatically. Every quarter when ABS releases new data — this site updates. Every time a fact-check organisation rates a political statement — this site updates. Every time a new budget is handed down — this site updates. The goal is a permanent, living, maintained public record of Australian government financial performance. Searchable. Comparable. Always current. Always cited. This isn't a media project. It's infrastructure. The same way roads and electricity are infrastructure that Australians depend on — accurate, readable, primary-source financial data should be infrastructure too. It should just exist. For everyone. For free.",
      expert: "Roadmap: Phase 1 (current) manual updates. Phase 2: automated agent fetches ABS/RBA/ANAO quarterly, updates lib/pm-data.ts, opens PR for human review. Phase 3: fact-check DB integration. Phase 4 (optional): state governments. See AGENT.md. Design goal: living public record, not snapshot. No editorial gatekeeping of updates — methodology is fixed; data updates are evidence-based and reviewable. Infrastructure framing: public good, non-rival, verifiable.",
    },
  },
  {
    headline: "THIS IS AN OPEN SOURCE PROJECT.",
    body: {
      kid: "Found a mistake? Tell us on GitHub with the source document — we'll fix it. Want to add something? Fork the repo and send a pull request. Broken link? Tell us. Think a method is unfair? Open a Discussion; we'll debate it and change it if you're right. We especially want help with: checking numbers against the original documents, adding new years as they're released, and making the site easier to use. One rule: same rules for everyone. No favouring one party.",
      teen: "Found a data error? Raise a GitHub issue with the source document. We'll fix it within 48 hours. Want to add a new section? Fork the repo and submit a pull request. Found a broken source link? Tell us. Think a methodology is unfair? Open a GitHub Discussion. We'll debate it publicly and update the methodology if you're right. We're especially interested in: data verification against original source documents; additional historical years as CFS documents are released; opposition party policy analysis; accessibility improvements; mobile experience improvements. The only thing we ask: leave your party card at the door. The methodology has to be the same for everyone.",
      expert: "Contributing: CONTRIBUTING.md. Data verification: issue with incorrect value, correct value, source URL, page/table. Response SLA 48h; evidence public; credit in commit. PRs accepted: factual corrections with primary source; methodology changes applied to ALL parties; accessibility/UX; new data years. PRs rejected: different methodology by party; removal of data that disadvantages one party; AI prompt changes that introduce political bias. Agent contribution: AGENT.md.",
    },
  },
];

export const ABOUT_FINAL_STATEMENT =
  "The media has editors. Politicians have spin doctors. The numbers have neither. That's why we show you the numbers.";
